### ISSUE TITLE
🐛 [Bug]: panic: ./docs/swagger.yaml file does not exist

### ISSUE THREAD

**Issue by mkrueger12** [EinStack/glide#209]
I am deploying the latest release via helm.

`values.yaml` specification:

`image:
  repository: ghcr.io/einstack/glide
  tag: "0.0.3-rc.1-alpine"
  pullPolicy: IfNotPresent
  pullSecrets: []`

On startup I receive the following error:

```
2024-04-16T17:38:01.255Z        DEBUG   routers/config.go:36    Init router     {"routerID": "azure-latency"}
2024-04-16T17:38:01.255Z        DEBUG   routers/config.go:94    Init lang model {"router": "azure-latency", "model": "azure-gpt4-west"}
2024-04-16T17:38:01.255Z        DEBUG   routers/config.go:94    Init lang model {"router": "azure-latency", "model": "azure-gpt4-east"}
panic: ./docs/swagger.yaml file does not exist

goroutine 23 [running]:
github.com/gofiber/contrib/swagger.New({0xc00026ee90?, 0x1?, 0x1?})
        /go/pkg/mod/github.com/gofiber/contrib/swagger@v1.1.1/swagger.go:90 +0x845
glide/pkg/api/http.(*Server).Run(0xc0001f0e80)
        /build/pkg/api/http/server.go:40 +0xd4
glide/pkg/api.(*ServerManager).Start.func1()
        /build/pkg/api/servers.go:44 +0x76
created by glide/pkg/api.(*ServerManager).Start in goroutine 1
        /build/pkg/api/servers.go:41 +0x66
```

This is the first time I've experienced this error. Had success deploying it previously.

**Comment by mkrueger12** [comment]
Local testing does not surface the same error.

**Comment by mkrueger12** [comment]
This appears to also be in issue with `0.0.2-alpine`.

**Comment by roma-glushko** [comment]
Hm, good catch 👀  I'm wondering if this is related to migratation from hertz to fiber

**Comment by roma-glushko** [comment]
Seems like Fiber swagger integration lacks a way to embed the swagger file, so they have a PR to bring that:
https://github.com/gofiber/contrib/pull/1069

**Comment by roma-glushko** [comment]
@mkrueger12 I have it: https://github.com/EinStack/glide/pull/211 Had to switch to another official swagger ext and serve swagger spec via Glide API but it should work now 😌

**Comment by mkrueger12** [comment]
Great. I'll be able to take a look tomorrow. Thanks.

**Comment by mkrueger12** [comment]
@roma-glushko Seeing the same issue with swagger.json

**Comment by roma-glushko** [comment]
This is interesting. I will try to use dockercompose to pull the image and reproduce the issue that way

**Comment by roma-glushko** [comment]
@mkrueger12 This is what I see trying to run the image in docker:

![2024-04-18_22-13-45](https://github.com/EinStack/glide/assets/9402690/6e8480ba-4013-43c9-b703-b28e959e91bd)

I'm little bit surprised to see swagger.json in there. In v0.0.3 I have used go:embed directive to pull its content into the binary. So the binary itself doesn't depend on any files anymore. Could you please check if 0.0.3 was really pulled there?

**Comment by roma-glushko** [comment]
ANd there is some issue with build info, so I've filled a task for look into it: https://github.com/EinStack/glide/issues/217

**Comment by mkrueger12** [comment]
@roma-glushko  I also could not reproduce it locally. I'll check the logs/build

**Comment by mkrueger12** [comment]
Looks like the build was correct.

**Comment by mkrueger12** [comment]
Issue appears resolved. It appears to be related to specifying "latest-alpine" instead of "0.0.3-alpine" where "latest-alpine" throws the error.

**Comment by roma-glushko** [comment]
@mkrueger12 I think I have got it. `latest` tags + Pod strategy to pull images only if not present on the node may lead to pulling the image from the node cache. We expect that nodes in clusters will rotate frequently enough to avoid this situation. Otherwise, our users can easily specify the exact version to be completely in charge of updates (this is recommended and set by default in the Glide helm chart).
