### ISSUE TITLE
[Config] Render all Durations as human-readable string

### ISSUE THREAD

**Issue by roma-glushko** [EinStack/glide#238]
Let's render all Durations like retry.min_delay, retry.max_delay, client.timeout as human-friendly strings (e.g. 5s):

![2024-05-05_15-34-13](https://github.com/EinStack/glide/assets/9402690/b23a383d-926c-4a23-8bf5-c90da1d8e49a)

**Comment by ppmdo** [comment]
Hi, nice project!

I can take a look into this. Please assign it to me.

**Comment by roma-glushko** [comment]
@ppmdo appreciate that Pablo 🙏

**Comment by daesu** [comment]
Apologies @roma-glushko  @ppmdo  I didn't see you had taken this. I have a PR [here](https://github.com/EinStack/glide/pull/250)

**Comment by roma-glushko** [comment]
Closed in #253 ✅
